version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: docker build -t ${DOCKER_IMAGE}:$(echo $CIRCLE_BRANCH | sed -e 's/\//-/g') .
      - run: DOCKER_TAG=$(echo $CIRCLE_BRANCH | sed -e 's/\//-/g') ./docker-test.sh
      - run: $(aws ecr get-login --no-include-email --region us-west-2)
      - run: docker push ${DOCKER_IMAGE}:$(echo $CIRCLE_BRANCH | sed -e 's/\//-/g')
      - store_artifacts:
          path: logs

  build-sdk:
    machine: true
    steps:
      - run: sudo apt-get update && sudo apt-get install rng-tools
      - run: sudo rngd -o /dev/random -r /dev/urandom
      - checkout
      - run: cd client/crypto-sdk && ./docker-build.sh

  deploy:
    machine: true
    steps:
      - checkout
      - run: cd deploy/cloudformation && npm install && ./create-stacks.sh

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - build-sdk
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
