version: 2
jobs:
  build-server:
    machine: true
    steps:
      - checkout
      - run: ./.circleci/setup-rngd.sh
      - run: ./docker/build-server-base.sh
      - run: ./docker-build.sh
      - run: ./docker-test.sh
      - run: $(aws ecr get-login --no-include-email --region us-west-2)
      - run: docker push ${DOCKER_IMAGE}
      - store_artifacts:
          path: logs

  build-sdk:
    machine: true
    steps:
      - checkout
      - run: ./.circleci/setup-rngd.sh
      - run: ./docker/build-sdk-base.sh
      - run: ./docker/build-sdk.sh
      - run: ./.circleci/export-artifacts.sh
      - store_artifacts:
          path: logs

  deploy:
    machine: true
    steps:
      - checkout
      - run: echo LOGZIO_API_KEY=$LOGZIO_API_KEY >> deploy/bootstrap/.env-secrets
      - run: $(aws ecr get-login --no-include-email --region us-west-2)
      - run: ./.circleci/docker-pull.sh
      - run: ./.circleci/deploy.sh

  e2e-testnet:
    machine: true
    steps:
      - checkout
      - run: $(aws ecr get-login --no-include-email --region us-west-2)
      - run: ./.circleci/docker-pull.sh
      - run: ./.circleci/e2e-testnet.sh

workflows:
  version: 2
  build:
    jobs:
      - build-sdk
      - build-server
      # - build-server
      # - deploy:
      #     requires:
      #       - build-server
      #     filters:
      #       branches:
      #         only: master
      # - e2e-testnet:
      #     requires:
      #       - deploy
      #     filters:
      #       branches:
      #         only: master
